apiVersion: ai.ai.example.com/v1
kind: InferenceService
metadata:
  labels:
    app.kubernetes.io/name: inferenceservice
    app.kubernetes.io/instance: inferenceservice-sample
    app.kubernetes.io/part-of: inference-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: inference-operator
  name: test-inference
spec:
  # TODO(user): Add fields here
  modelName: sentiment-analysis
  image: 172.17.0.1:5000/nginx:alpine
  imagePullPolicy: IfNotPresent
  replicas: 1
